// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/suliar/GFSender/quotes (interfaces: TwilioClient)

// Package twilio_mock is a generated GoMock package.
package twilio_mock

import (
	gomock "github.com/golang/mock/gomock"
	gotwilio "github.com/sfreiberg/gotwilio"
	reflect "reflect"
)

// MockTwilioClient is a mock of TwilioClient interface
type MockTwilioClient struct {
	ctrl     *gomock.Controller
	recorder *MockTwilioClientMockRecorder
}

// MockTwilioClientMockRecorder is the mock recorder for MockTwilioClient
type MockTwilioClientMockRecorder struct {
	mock *MockTwilioClient
}

// NewMockTwilioClient creates a new mock instance
func NewMockTwilioClient(ctrl *gomock.Controller) *MockTwilioClient {
	mock := &MockTwilioClient{ctrl: ctrl}
	mock.recorder = &MockTwilioClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockTwilioClient) EXPECT() *MockTwilioClientMockRecorder {
	return m.recorder
}

// SendSMS mocks base method
func (m *MockTwilioClient) SendSMS(arg0, arg1, arg2, arg3, arg4 string) (*gotwilio.SmsResponse, *gotwilio.Exception, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendSMS", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(*gotwilio.SmsResponse)
	ret1, _ := ret[1].(*gotwilio.Exception)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SendSMS indicates an expected call of SendSMS
func (mr *MockTwilioClientMockRecorder) SendSMS(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendSMS", reflect.TypeOf((*MockTwilioClient)(nil).SendSMS), arg0, arg1, arg2, arg3, arg4)
}
